name: Gildorym
authors: [Lucariatias, godpuppet, melodichand]
version: 2.1.8
main: com.gildorymrp.gildorym.Gildorym
commands:
    newcharacter:
        usage: /<command>
        description: Resets all character data
    setname:
        usage: /cmd [name] <name> <name> <name> <name>
        description: Sets your surname
    rollinfo:
        usage: /<command>
        description: Shows your roll info
    roll:
        usage: /<command> [roll]
        description: Rolls, broadcasting the result to players within 32 blocks
    renameitem:
        usage: /<command> [name]
        description: Renames the item in hand
    setlore:
        usage: /<command> [loretext]
        description: Sets the lore text on the item in hand
    addlore:
        usage: /<command> [loretext]
        description: Adds additional lore text to the item in hand
