name: Gildorym
authors: [Lucariatias, godpuppet, melodichand, Hohahihehu]
version: 2.1.8
main: com.gildorymrp.gildorym.Gildorym
commands:
    newcharacter:
        usage: /<command>
        description: Resets all character data
    setname:
        usage: /cmd <name> <name> <name> <name> <name>
        description: Sets your name
    setnameother:
        usage: /cmd [user] <name> <name> <name> <name> <name>
    rollinfo:
        usage: /<command>
        description: Shows your roll info
    roll:
        usage: /<command> [roll]
        description: Rolls, broadcasting the result to players within 24 blocks
    addlore:
        usage: /<command> [loretext]
        description: Adds additional lore text to the item in hand.
    removelore:
        usage: /<command>
        description: Removes lore text from the item in hand.
    renameitem:
        usage: /<command> [name]
        description: Changes the display name of the item in hand.
    setlore: 
        usage: /<command> [loretext]
        description: Sets the lore text of the item in hand.
    signitem:
        usage: /<command>
        description: Signs the user's name onto the item in hand.
permissions:
    gildorym.setname:
        description: Allows you to set your name.
        default: op
    gildorym.setname.title:
        description: Allows you to set your title.
        default: op
    gildorym.setname.other:
        description: Allows you to set someone elses name.
        default: op
    gildorym.mec
        description: Allows you to use metadata editing commands.
        default: op
